import '../../../node_modules/lightpick/lightpick.js'
import '../../common.blocks/header/header.js'
import '../../common.blocks/footer/footer.js'
import '../../common.blocks/total-price-card/total-price-card.js'
import '../../common.blocks/small.blocks/donut-diagram/donut-diagram.js'
import '../../main.less'
import './description-page.less'
