import '../../../node_modules/lightpick/lightpick.js'
import '../../common.blocks/header/header.js'
import '../../common.blocks/footer/footer.js'
import '../../common.blocks/cards-for-rooms/cards-for-rooms.js'
import '../../common.blocks/choose-options/choose-options.js'
import '../../main.less'
import './search-page.less'
